syntax = "proto3";

package ethereum.eth.v1alpha1;

import "proto/engine/v1/gloas.proto";
import "proto/eth/ext/options.proto";
import "proto/prysm/v1alpha1/beacon_core_types.proto";

option csharp_namespace = "Ethereum.Eth.v1alpha1";
option go_package = "github.com/OffchainLabs/prysm/v6/proto/prysm/v1alpha1;eth";
option java_multiple_files = true;
option java_outer_classname = "ExecutionChunkProto";
option java_package = "org.ethereum.eth.v1alpha1";
option php_namespace = "Ethereum\\Eth\\v1alpha1";

message ExecutionChunkSidecar {
  ethereum.engine.v1.ExecutionChunk chunk = 1;
  repeated bytes inclusion_proof = 2 [(ethereum.eth.ext.ssz_size) = "13,32"];
  SignedBeaconBlockHeader signed_block_header = 3;
}

message ChunkAccessListSidecar {
  uint64 chunk_index = 1;
  bytes chunk_access_list = 2 [ (ethereum.eth.ext.ssz_max) = "16777216" ];
  repeated bytes inclusion_proof = 3 [(ethereum.eth.ext.ssz_size) = "13,32"];
  SignedBeaconBlockHeader signed_block_header = 4;
}
