syntax = "proto3";

package ethereum.engine.v1;

import "proto/eth/ext/options.proto";
import "proto/engine/v1/execution_engine.proto";

option csharp_namespace = "Ethereum.Engine.V1";
option go_package = "github.com/prysmaticlabs/prysm/v5/proto/engine/v1;enginev1";
option java_multiple_files = true;
option java_outer_classname = "GloasProto";
option java_package = "org.ethereum.engine.v1";
option php_namespace = "Ethereum\\Engine\\v1";

message ExecutionBundleGloas {
  ExecutionPayloadHeaderGloas payload = 1;
  bytes value = 2;
  BlobsBundleV2 blobs_bundle = 3;
  bool should_override_builder = 4;
  repeated bytes execution_requests = 5;
  repeated ExecutionChunkBundle chunks = 6;
}

// EIP-8101

message ExecutionChunkHeader {
  uint64 index = 1;
  bytes chunk_access_list_hash = 2 [ (ethereum.eth.ext.ssz_size) = "32" ];
  uint64 pre_chunk_tx_count = 3;
  uint64 pre_chunk_gas_used = 4;
  uint64 pre_chunk_blob_gas_used = 5;
  bytes txs_root = 6 [ (ethereum.eth.ext.ssz_size) = "32" ];
  uint64 gas_used = 7;
  uint64 blob_gas_used = 8;
  bytes withdrawals_root = 9 [ (ethereum.eth.ext.ssz_size) = "32" ];
}

message ExecutionChunk {
  ExecutionChunkHeader chunk_header = 1;
  repeated bytes transactions = 2 [
    (ethereum.eth.ext.ssz_size) = "?,?",
    (ethereum.eth.ext.ssz_max) = "1048576,1073741824"
  ];
  repeated Withdrawal withdrawals = 3 [ (ethereum.eth.ext.ssz_max) = "withdrawal.size" ];
}

message ExecutionChunkBundle {
  ExecutionChunkHeader chunk_header = 1;
  repeated bytes transactions = 2 [
    (ethereum.eth.ext.ssz_size) = "?,?",
    (ethereum.eth.ext.ssz_max) = "1048576,1073741824"
  ];
  repeated Withdrawal withdrawals = 3 [ (ethereum.eth.ext.ssz_max) = "withdrawal.size" ];
  bytes chunk_access_list = 4 [ (ethereum.eth.ext.ssz_max) = "16777216" ];
}
